// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Todo(props) {
  return React.createElement("div", undefined, React.createElement("p", undefined, "Id: " + String(props.id) + ""), React.createElement("p", undefined, "" + props.title + ""), React.createElement("div", undefined, "Completed?: ", React.createElement("input", {
                      checked: props.isCompleted,
                      disabled: true,
                      type: "checkbox"
                    })));
}

var make = Todo;

export {
  make ,
}
/* react Not a pure module */
