// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Todo(props) {
  var isCompletedString = props.isCompleted ? "Yes" : "No";
  return React.createElement("div", undefined, React.createElement("p", undefined, "Id: " + String(props.id) + ""), React.createElement("p", undefined, "" + props.title + ""), React.createElement("p", undefined, "Completed? " + isCompletedString + ""));
}

var make = Todo;

export {
  make ,
}
/* react Not a pure module */
