// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function User(props) {
  return React.createElement("div", undefined, React.createElement("p", undefined, "Name: " + props.fullName + ""), React.createElement("p", undefined, "Username: " + props.username + ""), React.createElement("p", undefined, "Company: " + props.companyName + ""));
}

var make = User;

export {
  make ,
}
/* react Not a pure module */
