// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Link from "next/link";

function Index$default(props) {
  return React.createElement("div", undefined, React.createElement(Link, {
                  href: "/Users",
                  children: "Users"
                }), React.createElement(Link, {
                  href: "/Todos",
                  children: "Todos"
                }));
}

var $$default = Index$default;

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
