// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Todo from "../components/Todo.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Navbar from "../components/Navbar.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

var initialState_todos = [];

var initialState = {
  todos: initialState_todos,
  inputValue: ""
};

function reducer(state, action) {
  if (typeof action === "number") {
    return {
            todos: Belt_Array.concat(state.todos, [{
                    id: state.todos.length + 1 | 0,
                    title: state.inputValue,
                    isCompleted: false
                  }]),
            inputValue: ""
          };
  }
  if (action.TAG === /* ChangeInput */0) {
    return {
            todos: state.todos,
            inputValue: action._0
          };
  }
  var index = action._0;
  return {
          todos: Belt_Array.mapWithIndex(state.todos, (function (arrIndex, todo) {
                  if (arrIndex === index) {
                    return {
                            id: todo.id,
                            title: todo.title,
                            isCompleted: !todo.isCompleted
                          };
                  } else {
                    return todo;
                  }
                })),
          inputValue: state.inputValue
        };
}

function Todos$default(props) {
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  var state = match[0];
  var handleChange = function ($$event) {
    var newValue = $$event.target.value;
    Curry._1(dispatch, {
          TAG: /* ChangeInput */0,
          _0: newValue
        });
  };
  return React.createElement("div", {
              className: "flex flex-col items-center gap-4 w-full max-w-screen-lg text-main"
            }, React.createElement(Navbar.make, {}), React.createElement("div", {
                  className: "text-2xl font-medium"
                }, "To-do List"), React.createElement("div", {
                  className: "flex flex-col items-center gap-1.5 w-full"
                }, React.createElement("input", {
                      className: "text-lg p-0.5 border border-secondary focus:border-main w-4/5 min-w-[280px]",
                      placeholder: "Enter to-do...",
                      type: "text",
                      value: state.inputValue,
                      onChange: handleChange
                    }), React.createElement("button", {
                      className: "ml-2 hover:bg-main hover:text-bg-color p-1.5 rounded text-lg",
                      onClick: (function (param) {
                          if (state.inputValue.length > 0) {
                            return Curry._1(dispatch, /* AddTodo */0);
                          }
                          
                        })
                    }, "Add To-do")), Belt_Array.mapWithIndex(state.todos, (function (index, todo) {
                    return React.createElement("div", {
                                key: String(todo.id),
                                className: "w-4/5 min-w-[280px]",
                                onClick: (function (param) {
                                    Curry._1(dispatch, {
                                          TAG: /* MarkComplete */1,
                                          _0: index
                                        });
                                  })
                              }, React.createElement(Todo.make, {
                                    id: todo.id,
                                    title: todo.title,
                                    isCompleted: todo.isCompleted
                                  }));
                  })));
}

var $$default = Todos$default;

export {
  initialState ,
  reducer ,
  $$default ,
  $$default as default,
}
/* Todo Not a pure module */
