// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Todo$default(props) {
  return React.createElement("div", undefined, "Todo");
}

var $$default = Todo$default;

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
