// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Todo from "../components/Todo.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxPPXReactSupport from "rescript/lib/es6/jsxPPXReactSupport.js";

var initialState_todos = [];

var initialState = {
  todos: initialState_todos,
  inputValue: ""
};

function reducer(state, action) {
  if (action) {
    return {
            todos: state.todos,
            inputValue: action._0
          };
  } else {
    return {
            todos: Belt_Array.concat(state.todos, [{
                    id: state.todos.length + 1 | 0,
                    title: state.inputValue,
                    isCompleted: false
                  }]),
            inputValue: ""
          };
  }
}

function Todos$default(props) {
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  var state = match[0];
  var handleChange = function ($$event) {
    var newValue = $$event.target.value;
    Curry._1(dispatch, /* ChangeInput */{
          _0: newValue
        });
  };
  return React.createElement("div", undefined, React.createElement("div", undefined, "Todo List"), React.createElement("input", {
                  type: "text",
                  value: state.inputValue,
                  onChange: handleChange
                }), React.createElement("button", {
                  onClick: (function (param) {
                      if (state.inputValue.length > 0) {
                        return Curry._1(dispatch, /* AddTodo */0);
                      }
                      
                    })
                }, "Add Todo"), Belt_Array.map(state.todos, (function (todo) {
                    return JsxPPXReactSupport.createElementWithKey(String(todo.id), Todo.make, {
                                id: todo.id,
                                title: todo.title,
                                isCompleted: todo.isCompleted
                              });
                  })));
}

var $$default = Todos$default;

export {
  initialState ,
  reducer ,
  $$default ,
  $$default as default,
}
/* Todo Not a pure module */
