// Generated by ReScript, PLEASE EDIT WITH CARE

import * as User from "../components/User.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxPPXReactSupport from "rescript/lib/es6/jsxPPXReactSupport.js";

function Users$default(props) {
  var match = React.useState(function () {
        return [];
      });
  var setUsersArray = match[1];
  var usersArray = match[0];
  React.useEffect((function () {
          var updateUsers = async function (url) {
            var response = await fetch(url);
            var json = await response.json();
            console.log(json);
            return Curry._1(setUsersArray, (function (param) {
                          return json;
                        }));
          };
          updateUsers("https://jsonplaceholder.typicode.com/users");
        }), []);
  var listOfUsers = Belt_Array.map(usersArray, (function (user) {
          return JsxPPXReactSupport.createElementWithKey(String(user.id), User.make, {
                      username: user.username,
                      fullName: user.name,
                      companyName: user.company.name
                    });
        }));
  var loading = React.createElement("div", undefined, "Fetching Users...");
  if (usersArray.length !== 0) {
    return listOfUsers;
  } else {
    return [loading];
  }
}

var $$default = Users$default;

export {
  $$default ,
  $$default as default,
}
/* User Not a pure module */
