// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Users$default(props) {
  return React.createElement("div", undefined, "Users");
}

var $$default = Users$default;

export {
  $$default ,
  $$default as default,
}
/* react Not a pure module */
